const store = [
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "",
    name: "",
    popular: false,
    price: 100,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3asd5308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3asd5308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3asd5308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3asd5308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "",
    name: "",
    popular: false,
    price: 0,
    size: 36,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
]

export default store
