// const store = [
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross1.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "women",
//     image: "",
//     name: "",
//     popular: false,
//     price: 100,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross1.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "men",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3asd5308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross1.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "kids",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross2.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "women",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross2.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "men",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3asd5308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross2.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "kids",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross3.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "women",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross3.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "men",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3asd5308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross3.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "kids",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross4.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "women",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross4.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "men",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3asd5308ab3ab8f8",
//   },
//   {
//     brandName: "Nike",
//     src: '../img/popularArrivals/cross4.jpg',
//     description: "",
//     descriptionFull: "",
//     category: "kids",
//     image: "",
//     name: "",
//     popular: false,
//     price: 0,
//     size: 36,
//     type: "Кросoвки",
//     _id: "5dc3ccbd92a65308ab3ab8f8",
//   },
//   {
//     brandName: "Adidas",
//     src: '../img/store/a1.jpg',
//     category: "men",
//     image: "",
//     name: "ADIDAS 3MC",
//     popular: false,
//     price: 65,
//     size: 44,
//     quantity: 0,
//     color: 'black',
//     _id: "4dc3ccbd52a60307",
//   },
// ]

// export default store
