  const store = [
  {
    brandName: "Nike",
    src: '../img/store/w1.webp',
    category: "women",
    image: "",
    name: "Nike RYZ 365",
    popular: false,
    price: 85,
    size: 36,
    color: 'black',
    _id: "5dc3ccbd92a65308",
  },
  {
    brandName: "Nike",
    src: '../img/store/w2.webp',
    category: "women",
    image: "",
    name: "Nike Air Force 1 Shadow",
    popular: false,
    price: 95,
    size: 38,
    color: 'black',
    _id: "5dc3ccbd92a65309",
  },
  {
    brandName: "Nike",
    src: '../img/store/w3.webp',
    category: "women",
    image: "",
    name: "Nike Air Force 1 Low",
    popular: true,
    price: 170,
    size: 38,
    color: 'grin',
    _id: "5dc3ccbd92a65307",
  },
  {
    brandName: "Nike",
    src: '../img/store/w4.webp',
    category: "women",
    image: "",
    name: "Nike Air Max Plus",
    popular: true,
    price: 135,
    size: 35,
    color: 'gray',
    _id: "5dc3ccbd92a65317",
  },
  {
    brandName: "Nike",
    src: '../img/store/w5.webp',
    category: "women",
    image: "",
    name: "Nike Low 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a60307",
  },
  {
    brandName: "Nike",
    src: '../img/store/w6.webp',
    category: "women",
    image: "",
    name: "Nike Air Mix ",
    popular: false,
    price: 105,
    size: 37,
    color: 'pink',
    _id: "5dc3ccbd52a60303",
  },
  {
    brandName: "Nike",
    src: '../img/store/w7.webp',
    category: "women",
    image: "",
    name: "Nike Air Max 65",
    popular: true,
    price: 75,
    size: 35,
    color: 'grin',
    _id: "5dc3ccbd52a60312",
  },
  {
    brandName: "Nike",
    src: '../img/store/w8.webp',
    category: "women",
    image: "",
    name: "Nike React Element 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a60307",
  },
]

export default store
