const store = [
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "https://picsum.photos/id/20/60",
    name: "Batman shoes",
    popular: false,
    price: 100,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "https://picsum.photos/id/21/60",
    name: "Nike for runing",
    popular: false,
    price: 23,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3asd5308asdb3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross1.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "https://picsum.photos/id/22/60",
    name: "Beach slippers",
    popular: false,
    price: 50,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92wswa65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "https://picsum.photos/id/23/60",
    name: "Pool shoes",
    popular: false,
    price: 22,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65hgth308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "https://picsum.photos/id/24/60",
    name: "Golf shoes",
    popular: false,
    price: 16,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3asd5308e3rab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross2.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "https://picsum.photos/id/25/60",
    name: "Nike sandals",
    popular: false,
    price: 110,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308ab37i7iab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "https://picsum.photos/id/26/60",
    name: "Shoes for some stupids",
    popular: false,
    price: 59,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92aswsqs65308ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "https://picsum.photos/id/27/60",
    name: "Arabic sandals",
    popular: false,
    price: 78,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3asd5308yki8o8iab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross3.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "https://picsum.photos/id/28/60",
    name: "Tennis valenki",
    popular: false,
    price: 45,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308awdw3r3rb3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "women",
    image: "https://picsum.photos/id/29/60",
    name: "Nike bestseller",
    popular: false,
    price: 23,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a65308asdgdb3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "men",
    image: "https://picsum.photos/id/30/60",
    name: "Just do it",
    popular: false,
    price: 50,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3asd530qewfrwt458ab3ab8f8",
  },
  {
    brandName: "Nike",
    src: '../img/popularArrivals/cross4.jpg',
    description: "",
    descriptionFull: "",
    category: "kids",
    image: "https://picsum.photos/id/31/60",
    name: "No more names",
    popular: false,
    price: 100,
    size: 36,
    quantity: 1,
    type: "Кросoвки",
    _id: "5dc3ccbd92a6q3r534635308ab3ab8f8",
  },
]

export default store
