  const store = [
  {
    brandName: "Nike",
    src: '../img/store/w1.webp',
    category: "men",
    categories: [{title: 'Men', titleValue: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike RYZ 365",
    popular: false,
    price: 85,
    size: 36,
    color: 'black',
    _id: "5dc3ccbd92a65308",
  },
  {
    brandName: "Nike",
    src: '../img/store/w2.webp',
    category: "men",
    categories: [{title: 'Men', titleValue: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Force 1 Shadow",
    popular: false,
    price: 95,
    size: 38,
    color: 'black',
    _id: "5dc3ccbd92a65309",
  },
  {
    brandName: "Nike",
    src: '../img/store/w3.webp',
    category: "men",
    categories: [{title: 'Men', titleValue: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Force 1 Low",
    popular: true,
    price: 170,
    size: 38,
    color: 'grin',
    _id: "5dc3ccbd92a65307",
  },
  {
    brandName: "Nike",
    src: '../img/store/w4.webp',
    category: "men",
    categories: [{title: 'Men', titleValue: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Max Plus",
    popular: true,
    price: 135,
    size: 35,
    color: 'gray',
    _id: "5dc3ccbd92a65317",
  },
  {
    brandName: "Nike",
    src: '../img/store/w5.webp',
    category: "men",
    categories: [{title: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Low 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a60307",
  },
  {
    brandName: "Nike",
    src: '../img/store/w6.webp',
    category: "men",
    categories: [{title: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Mix ",
    popular: false,
    price: 105,
    size: 37,
    color: 'pink',
    _id: "5dc3ccbd52a60303",
  },
  {
    brandName: "Nike",
    src: '../img/store/w7.webp',
    category: "men",
    categories: [{title: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Max 65",
    popular: true,
    price: 75,
    size: 35,
    color: 'grin',
    _id: "5dc3ccbd52a60312",
  },
  {
    brandName: "Nike",
    src: '../img/store/w8.webp',
    category: "men",
    categories: [{title: 'men', value: true}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike React Element 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a60307",
  },
  {
    brandName: "Nike",
    src: '../img/store/w1.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike RYZ 365",
    popular: false,
    price: 85,
    size: 36,
    color: 'black',
    _id: "5dc3ccbd92a653081",
  },
  {
    brandName: "Nike",
    src: '../img/store/w2.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Force 1 Shadow",
    popular: false,
    price: 95,
    size: 38,
    color: 'black',
    _id: "5dc3ccbd92a653092",
  },
  {
    brandName: "Nike",
    src: '../img/store/w3.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Force 1 Low",
    popular: true,
    price: 170,
    size: 38,
    color: 'grin',
    _id: "5dc3ccbd92a653073",
  },
  {
    brandName: "Nike",
    src: '../img/store/w4.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Max Plus",
    popular: true,
    price: 135,
    size: 35,
    color: 'gray',
    _id: "5dc3ccbd92a653174",
  },
  {
    brandName: "Nike",
    src: '../img/store/w5.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Low 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a603075",
  },
  {
    brandName: "Nike",
    src: '../img/store/w6.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Mix ",
    popular: false,
    price: 105,
    size: 37,
    color: 'pink',
    _id: "5dc3ccbd52a603036",
  },
  {
    brandName: "Nike",
    src: '../img/store/w7.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike Air Max 65",
    popular: true,
    price: 75,
    size: 35,
    color: 'grin',
    _id: "5dc3ccbd52a603127",
  },
  {
    brandName: "Nike",
    src: '../img/store/w8.webp',
    category: "women",
    categories: [{title: 'men', value: false}, {title: 'Women', titleValue: 'women', value: true}, {title: 'Kids', title: 'kids', value: false}],
    image: "",
    name: "Nike React Element 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a603078",
  },
  {
    brandName: "Nike",
    src: '../img/store/w1.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike RYZ 365",
    popular: false,
    price: 85,
    size: 36,
    color: 'black',
    _id: "5dc3ccbd92a6530811",
  },
  {
    brandName: "Nike",
    src: '../img/store/w2.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Air Force 1 Shadow",
    popular: false,
    price: 95,
    size: 38,
    color: 'black',
    _id: "5dc3ccbd92a6530922",
  },
  {
    brandName: "Nike",
    src: '../img/store/w3.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Air Force 1 Low",
    popular: true,
    price: 170,
    size: 38,
    color: 'grin',
    _id: "5dc3ccbd92a6530733",
  },
  {
    brandName: "Nike",
    src: '../img/store/w4.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Air Max Plus",
    popular: true,
    price: 135,
    size: 35,
    color: 'gray',
    _id: "5dc3ccbd92a6531744",
  },
  {
    brandName: "Nike",
    src: '../img/store/w5.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Low 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a6030755",
  },
  {
    brandName: "Nike",
    src: '../img/store/w6.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Air Mix ",
    popular: false,
    price: 105,
    size: 37,
    color: 'pink',
    _id: "5dc3ccbd52a6030366",
  },
  {
    brandName: "Nike",
    src: '../img/store/w7.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike Air Max 65",
    popular: true,
    price: 75,
    size: 35,
    color: 'grin',
    _id: "5dc3ccbd52a6031277",
  },
  {
    brandName: "Nike",
    src: '../img/store/w8.webp',
    category: "kids",
    categories: [{title: 'Men', titleValue: 'men', value: false}, {title: 'Women', titleValue: 'women', value: false}, {title: 'Kids', title: 'kids', value: true}],
    image: "",
    name: "Nike React Element 55",
    popular: false,
    price: 115,
    size: 37,
    color: 'grin',
    _id: "5dc3ccbd52a6030788",
  },
]

export default store
