export const getShopData = () => {
  const shopData = [
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "women",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab767",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "men",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3asd5308ab3646",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "kids",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3ab8545",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "women",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a6530425",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "men",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3asd5308ab53",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "kids",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3a54",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "women",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3a66",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "men",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3asd5308ab3ab855",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "kids",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3ab8f1",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "women",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3ab8f2",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "men",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3asd5308ab3aby6",
    },
    {
      brandName: "Nike",
      description: "",
      descriptionFull: "",
      category: "kids",
      image: "",
      name: "",
      popular: false,
      price: 0,
      size: 36,
      type: "Кросoвки",
      _id: "5dc3ccbd92a65308ab3aj67",
    },
  ]

  return Promise.resolve(shopData)

}


export const deleteItem = (id, token) => {
//   fetch(`http://localhost:3000/api/products/${id}`, {
//     method: 'DELETE',
//     headers: {
//         'content-type': 'application/json',
//         'Authorization': `Bearer ${token}`,
//     },
// }).then(res => res.json())
  return Promise.resolve({message: `success! id: ${id} is deleted`});
}
